# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelDesktopViewer < Formula
  desc "OpenTelemetry Desktop Viewer"
  homepage "https://github.com/CtrlSpice/otel-desktop-viewer"
  version "0.2.5-test"
  license "Apache-2.0"

  depends_on "go"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v0.2.5-test/otel-desktop-viewer_homebrew_MacOS_arm64.tar.gz"
      sha256 "a0832f3504a05791037e252e68f2dfadfd5f766fed69e537f8920e27d0270c16"

      def install
        bin.install "otel-desktop-viewer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v0.2.5-test/otel-desktop-viewer_homebrew_Linux_arm64.tar.gz"
      sha256 "b60e2b88a25ee5cfa5caa4b54ca2bc3234630acb4c25637ca80d8f174ad4628c"
      def install
        bin.install "otel-desktop-viewer"
      end
    end
  end

  def caveats
    <<~EOS
      To start the viewer, run:
        otel-desktop-viewer
    EOS
  end

  test do
    system "#{bin}/otel-desktop-viewer", "--version"
  end
end
