# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelDesktopViewer < Formula
  desc "OpenTelemetry Desktop Viewer"
  homepage "https://github.com/CtrlSpice/otel-desktop-viewer"
  version "0.2.0"
  license "Apache-2.0"

  depends_on "go"

  on_macos do
    url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v0.2.0/otel-desktop-viewer_homebrew_MacOS_x86_64.tar.gz"
    sha256 "0eb16576278d81c02358f35d7b9753720829b827d7aaac165046f97d015a6722"

    def install
      bin.install "otel-desktop-viewer"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the OtelDesktopViewer
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v0.2.0/otel-desktop-viewer_homebrew_Linux_x86_64.tar.gz"
      sha256 "0d758df15093df1ebe7f861bb8c1047dbf2c3a50d5cdb04ceacbbcf2a33ab3de"
      def install
        bin.install "otel-desktop-viewer"
      end
    end
  end

  def caveats
    <<~EOS
      To start the viewer, run:
        otel-desktop-viewer
    EOS
  end

  test do
    system "#{bin}/otel-desktop-viewer", "--version"
  end
end
