# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelDesktopViewer < Formula
  desc "OpenTelemetry Desktop Viewer"
  homepage "https://github.com/CtrlSpice/otel-desktop-viewer"
  version "0.2.4"
  license "Apache-2.0"

  depends_on "go"

  on_macos do
    url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v0.2.4/otel-desktop-viewer_homebrew_MacOS_x86_64.tar.gz"
    sha256 "4790678f8e40fd04b6a19e6a6e384b94847b4aab3c58b91be3f9ea741469f9a2"

    def install
      bin.install "otel-desktop-viewer"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the OtelDesktopViewer
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v0.2.4/otel-desktop-viewer_homebrew_Linux_x86_64.tar.gz"
      sha256 "f931194eedeb8813b50a372a284f636a337d084d668775194ef3ce5b53b6b8e2"
      def install
        bin.install "otel-desktop-viewer"
      end
    end
  end

  def caveats
    <<~EOS
      To start the viewer, run:
        otel-desktop-viewer
    EOS
  end

  test do
    system "#{bin}/otel-desktop-viewer", "--version"
  end
end
