# This file was generated by GoReleaser. DO NOT EDIT.
cask "otel-desktop-viewer" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "cddbb91d7161b32c5be0348954bbe3da56ef2b9092e23766d988773c1e776962"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a689226330ccd7af3984ccb991c780e195703f52cd09dba7f2f924d10de15ce2"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "813141fb6a8102d11ca1a8a86cd520ebee3af6e816e793b4ff2d8020a9d16f6b"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0df88c1c9ce50c2bef71cfcb063c7d4912cfa3ec986f5100990d4112fd696b82"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_linux_arm64.tar.gz"
    end
  end

  name "otel-desktop-viewer"
  desc "otel-desktop-viewer is a CLI tool for receiving OpenTelemetry traces, metrics, and logs on your local machine."
  homepage "https://github.com/CtrlSpice/otel-desktop-viewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otel-desktop-viewer"

  # No zap stanza required

  caveats <<~EOS
    To start the viewer, run:
      otel-desktop-viewer
  EOS
end
