# This file was generated by GoReleaser. DO NOT EDIT.
cask "otel-desktop-viewer" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "da34055ab1389f26729aad3f81a8ea9a12826ab38033544556735e944cf534db"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d2b6411c17e1b9833a14a026dd38f5764b1669387533eb6a4ba64cc84590d5bb"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "589b461d39c10ccc0c46434c72e36a80019f567f99c9dff8069e12b51e2b22e7"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ca73c5aed0d1ed8e40fad25d96001ba97d9445c90bef8254bfae4ce459d341e2"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_linux_arm64.tar.gz"
    end
  end

  name "otel-desktop-viewer"
  desc "otel-desktop-viewer is a CLI tool for receiving OpenTelemetry traces, metrics, and logs on your local machine."
  homepage "https://github.com/CtrlSpice/otel-desktop-viewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otel-desktop-viewer"

  # No zap stanza required

  caveats <<~EOS
    To start the viewer, run:
      otel-desktop-viewer
  EOS
end
