# This file was generated by GoReleaser. DO NOT EDIT.
cask "otel-desktop-viewer" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "d60d31860d04a9965626d3185e8c5cfa1689dc6f1fff195f4101e909d728473f"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e48d1ca9065e7fbfeb12db1e062305dd80699e9934e282bc0e97632d2fc6bde5"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d19af081108b7c8cfbdba365b5c09bd1d8635639032e4466204ba14777491403"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7784eaef46ade868fdef0bf567ed625f7d9bf1fc7ad959ffd74a869606386bcf"
      url "https://github.com/CtrlSpice/otel-desktop-viewer/releases/download/v#{version}/otel-desktop-viewer_homebrew_linux_arm64.tar.gz"
    end
  end

  name "otel-desktop-viewer"
  desc "otel-desktop-viewer is a CLI tool for receiving OpenTelemetry traces, metrics, and logs on your local machine."
  homepage "https://github.com/CtrlSpice/otel-desktop-viewer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otel-desktop-viewer"

  # No zap stanza required

  caveats <<~EOS
    To start the viewer, run:
      otel-desktop-viewer
  EOS
end
